### ISSUE TITLE
后续是否会增加推送功能？

### ISSUE THREAD

**Issue by FengZhengYa** [Xiaomi-mimc/operation-manual#1]
后续是否增加推送功能，还是有开发者自己来实现？

**Comment by hmxCoder** [comment]
这个推送功能是指服务端向客户端发送消息么？这个推送消息已经有了，参见https://github.com/Xiaomi-mimc/operation-manual#%E6%8E%A8%E9%80%81%E6%B6%88%E6%81%AF
如果是更全面的推送的话，有小米推送的。

如果又更多疑问，为方便交流，请进qq群：小米即时消息云沟通群 469123835

谢谢～
